// WARNING!! DO NOT EDIT THIS FILE (automatically generated)
// File created Fri Oct 11 15:55:10 2013 by make_registers v15
//
// (C) Copyright 2008, Qux Corporation
//     All rights reserved.
//
//		       PROPRIETARY INFORMATION
//
// The information contained in this file is the property of Qux Corporation
// Except as specifically authorized in writing by Qux, the holder of this file
// shall keep all information contained herein confidential and shall protect
// same in whole or in part from disclosure and dissemination to all third
// parties and shall use same for operation and maintenance purposes only.

// RW register definitions
`define DAT_I_DLY_INDEX 15:0

`define REG_BITS_W 15:0
`define REG_W_NBITS 16

// R register definitions
`define VERSION_AD 7'h7e
`define VERSION_INDEX 15:0

`define REG_BITS_R 15:0
`define REG_R_NBITS 16

// W register definitions

// control signal definitions
`define CLK_I_INDEX 0
`define VERSION_RD_INDEX 1

`define REG_BITS_CTL 1:0
`define REG_CTL_NBITS 2

`define REG_COUNT 1
`define REG_ADDRWIDTH 7
`define REG_DATAWIDTH 16
