// WARNING!! DO NOT EDIT THIS FILE (automatically generated)
// File created Fri Oct 11 15:55:10 2013 by make_registers v15
//
// (C) Copyright 2008, Qux Corporation
//     All rights reserved.
//
//		       PROPRIETARY INFORMATION
//
// The information contained in this file is the property of Qux Corporation
// Except as specifically authorized in writing by Qux, the holder of this file
// shall keep all information contained herein confidential and shall protect
// same in whole or in part from disclosure and dissemination to all third
// parties and shall use same for operation and maintenance purposes only.

//  RW register definitions

//  W register definitions
